---
title: v1cferr · Homelab
startUrl: https://dash.v1cferr.dev
theme: dark
color: slate
headerStyle: boxed
layout:
  Mídia:
    style: row
    columns: 2
  Downloads & Indexadores:
    style: row
    columns: 4
  IA:
    style: row
    columns: 2
  Projetos:
    style: row
    columns: 2
