-- ── Appearance: general plus decoration plus animations ────────────────────
-- Ported from the Arch look-and-feel.conf (Tokyo Night), adapted to the Lua 0.55 API.

-- The palette comes from Nix (my.theme): a table generated by home/desktop/palette.nix. Hexes
-- WITHOUT '#'; the borders/shadow below assemble rgba(<hex><alpha>). Switching the theme
-- recolors everything.
local C = dofile(os.getenv("HOME") .. "/.config/theme/hypr-colors.lua")

-- general: thin gaps/border plus a GRADIENT border (blue to magenta at 45 degrees). In the Lua
-- API the gradient is the table { colors={...}, angle=N }; the hyprlang string does not stick.
hl.config({
  general = {
    gaps_in = 3,
    gaps_out = 4,
    border_size = 1,
    ["col.active_border"]   = { colors = { "rgba(" .. C.blue .. "55)", "rgba(" .. C.magenta .. "44)" }, angle = 45 },
    ["col.inactive_border"] = "rgba(" .. C.border .. "44)",
    resize_on_border = false, -- it does not resize by clicking the border/gap
    allow_tearing = false,    -- no tearing (read the wiki before turning it on)
    layout = "scrolling",     -- an infinite tape on ALL the workspaces (native in 0.55); the binds are in keybinds.lua
  },
  -- decoration: rounded corners plus blur plus shadow. The windows' opacity lives in the global
  -- window_rule (rules.lua): 0.98 active / 0.96 inactive.
  decoration = {
    rounding = 10,
    shadow = {
      enabled = true,
      range = 6,
      render_power = 3,
      color = "rgba(" .. C.shadow .. "ee)",
    },
    blur = {
      enabled = true,
      size = 6,
      passes = 2,
      noise = 0.01,
      contrast = 0.9,
      brightness = 0.8,
      new_optimizations = true,
      vibrancy = 0.2,
    },
  },
  -- The tape: 1 window per screen. The only value away from the default (0.5); the other 6 of
  -- `scrolling` already are what we want, so they are not written here. Per column you can shrink
  -- with SUPER+ALT+,/. and the whole tape with SUPER+CTRL+,/. (keybinds.lua).
  -- The `dwindle` block left along with the layout: no workspace uses dwindle anymore.
  scrolling = {
    column_width = 1.0,
  },
  misc = {
    force_default_wallpaper = 0,  -- without the default anime wallpaper
    disable_hyprland_logo = true, -- without the background logo (we use our own wallpaper)
    -- VRR (G-Sync) only in fullscreen games. The LG UltraGear is G-Sync Compatible; on the Arc
    -- (xe) the freeze NVIDIA used to give on the lockscreen does NOT reproduce (which is why the
    -- always-on vrr=1 was vetoed on Arch; the history is in lockscreen.nix). 2 is safe.
    vrr = 2,
    -- A safety net against a lockout: if hyprlock dies during teardown (waking from dpms, say),
    -- relaunching `hyprlock` from a TTY reattaches the locked session instead of refusing, which
    -- avoids the "sudo reboot" to escape an orphaned lock screen.
    allow_session_lock_restore = true,
  },
})

-- ── Animations ──────────────────────────────────────────────────────────────
-- Custom beziers through hl.curve (hyprlang's old `bezier=`). "default" and "linear" are
-- Hyprland's built-ins; the four below are ours.
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },    { 0.32, 1 }   } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 }   } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },   { 0.75, 1.0 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },    { 0.1, 1 }    } })

hl.config({ animations = { enabled = true } })

-- leaf=the animation's name, speed=the duration (lower is faster), bezier=the curve,
-- style=the variation.
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
