-- ── The environment (hl.env) ───────────────────────────────────────────────
-- The cursor comes from Nix (my.theme.cursor): the same table generated by palette.nix that the
-- appearance uses, since this .lua is a hot-reload symlink and Nix does not interpolate in here.
-- Data generated by Nix, with a SELF-CONTAINED FALLBACK: if the file is missing (the 1st boot
-- before the rebuild, or new data not generated yet), the dofile BLOWS UP and aborts the config,
-- and since "autostart" comes later in the load order, the session comes up with no services.
-- Do NOT use a global helper: Hyprland does not share globals between the dofile calls.
local ok_T, T = pcall(dofile, os.getenv("HOME") .. "/.config/theme/hypr-colors.lua")
if not ok_T or type(T) ~= "table" then T = { cursorTheme = "Bibata-Modern-Ice", cursorSize = "24" } end

-- XCURSOR_* covers XWayland/legacy apps and Hyprland's fallback; HYPRCURSOR_* is the native
-- format (it falls back to XCursor when the theme has no hyprcursor variant).
-- GTK apps pick the cursor up from gsettings (home/theme.nix), not from here.
hl.env("XCURSOR_THEME", T.cursorTheme)
hl.env("XCURSOR_SIZE", T.cursorSize)
hl.env("HYPRCURSOR_THEME", T.cursorTheme)
hl.env("HYPRCURSOR_SIZE", T.cursorSize)

-- The Qt/KDE theme (Dolphin): it makes Qt follow the dark GTK. The qt module (home/theme.nix)
-- already sets this as a session var, but on Wayland the session does not always load it, so
-- pinning it here guarantees the dark look in apps opened by Hyprland.
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_STYLE_OVERRIDE", "adwaita-dark")

-- Qt runs natively on Wayland (with an xcb fallback): flameshot needs this to position the
-- overlay/picker correctly, and xcb covers any Qt app with no Wayland.
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
