-- ── Keybinds (parity with the Arch/Kingston) ────────────────────────────────
-- Data generated by Nix, with a SELF-CONTAINED FALLBACK: if the file is missing (the 1st boot
-- before the rebuild, or new data not generated yet), the dofile BLOWS UP and aborts the config,
-- and since "autostart" comes later in the load order, the session comes up with no services.
-- Do NOT use a global helper: Hyprland does not share globals between the dofile calls.
local ok_M, M = pcall(dofile, os.getenv("HOME") .. "/.config/theme/monitors.lua")
if not ok_M or type(M) ~= "table" then M = { primary = "DP-2", secondary = "HDMI-A-3" } end

local mainMod = "SUPER"

-- The programs the binds below call (tools adapted to NixOS).
local terminal       = "kitty"            -- SUPER+RETURN
local terminalWithAi = "kitty claude"     -- SUPER+BACKSPACE (Claude Code in the terminal)
local launcherApps   = "rofi -show drun -theme launcher" -- SUPER+Q (.desktop apps; icons plus recency)
local launcherRun    = "rofi -show run -theme launcher"  -- SUPER+R (binaries on the PATH)
local fileManager    = "dolphin"          -- SUPER+E [it used to be thunar]
local sound          = "pavucontrol"      -- SUPER+S (the audio mixer)
local bluetooth      = "blueman-manager"  -- SUPER+B

-- The main apps and actions
hl.bind(mainMod .. " + Q",         hl.dsp.exec_cmd(launcherApps))                 -- launcher (apps)
hl.bind(mainMod .. " + R",         hl.dsp.exec_cmd(launcherRun))                  -- launcher (run)
hl.bind(mainMod .. " + RETURN",    hl.dsp.exec_cmd(terminal))                     -- terminal
hl.bind(mainMod .. " + BACKSPACE", hl.dsp.exec_cmd(terminalWithAi))               -- terminal with AI (Claude Code)
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager))                  -- files (Dolphin)
hl.bind(mainMod .. " + S",         hl.dsp.exec_cmd(sound))                        -- audio mixer
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd(bluetooth))                    -- bluetooth
hl.bind(mainMod .. " + C",         hl.dsp.window.close())                         -- close the window
hl.bind(mainMod .. " + V",         hl.dsp.window.float({ action = "toggle" }))    -- float
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))  -- fullscreen
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo())                        -- pseudo (a dwindle thing; a no-op on scrolling, but it answers ok and raises no toast)
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("hyprctl reload"))             -- reload the config
-- The cheatsheet: it lists ALL the binds in rofi, generated from this file at runtime
-- (home/desktop/cheatsheet.nix). H and not "/" because Moonlight does not send the ABNT2 "/".
hl.bind(mainMod .. " + H",         hl.dsp.exec_cmd("keybinds-cheatsheet"))        -- help: the shortcut list
-- lock: loginctl to logind to hypridle's lock_cmd (home/lockscreen.nix); it never duplicates hyprlock.
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("loginctl lock-session"))      -- lock the screen

-- The "/" key over remote access: Moonlight does NOT send the ABNT2 "/ ?" key (bug #1789, an
-- international key). It remaps SCROLL LOCK (an idle key; this TKL has no Menu) to "/" and
-- Shift+ScrollLock to "?", through send_shortcut (a NATIVE Hyprland dispatcher, which sends the
-- keysym straight to the active window, independent of the layout and with no external exec,
-- unlike wtype, which did not inject through the bind). It keeps the ABNT2 and works locally too.
-- key = "code:97" and NOT "slash": send_shortcut's resolveKeycode sweeps the keymap with
-- xkb_state_key_get_one_sym, which respects the modifiers HELD AT THAT MOMENT, so it only finds a
-- keysym at the ACTIVE level. With Shift held (the "?" bind) no keycode produces `slash` (they
-- produce `question`), giving "send_shortcut: key not found", and the "?" never came out. The
-- `code:` prefix short-circuits BEFORE touching the xkb state, so it is immune to modifiers.
-- 97 = <AB11>, the ABNT2 "/ ?" key (evdev KEY_RO 89 plus 8); it checks out against
-- `xkbcli compile-keymap --layout br --variant abnt2`.
hl.bind("Scroll_Lock",         hl.dsp.send_shortcut({ mods = 0,       key = "code:97", window = "activewindow" }))  -- "/"
hl.bind("SHIFT + Scroll_Lock", hl.dsp.send_shortcut({ mods = "SHIFT", key = "code:97", window = "activewindow" }))  -- "?" (Shift+/)

-- clipboard: cliphist's history in rofi with a PREVIEW (an image thumbnail plus an icon per file
-- type); the choice goes back to the clipboard (paste it with Ctrl+V). The script and the Tokyo
-- Night theme are in home/desktop/clipboard.nix.
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("clipboard-menu"))

-- VPN (Arch parity): SUPER+N = UFSCar (GlobalProtect), SHIFT+N = FAI (SonicWall/nxBender),
-- CTRL+N disconnects everything. On-demand systemd services (system/net/vpn.nix); the `vpn` CLI
-- brings them up with no password through a polkit rule.
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("vpn connect ufscar"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("vpn connect fai"))
hl.bind(mainMod .. " + CTRL + N",  hl.dsp.exec_cmd("vpn disconnect all"))

-- Restarting Quickshell (rarely needed, since it hot-reloads the QML on save; useful only when
-- the process hangs). `qs kill` stops the instance, `qs` brings it up.
hl.bind(mainMod .. " + ESCAPE",    hl.dsp.exec_cmd("qs-restart")) -- restart Quickshell (a Repeater delegate does not pick up the hot-reload)

-- Minimize: it sends the OTHER windows of the workspace to special:minimized (a toggle).
hl.bind(mainMod .. " + M",         hl.dsp.exec_cmd("minimize-others"))
hl.bind(mainMod .. " + CTRL + M",  hl.dsp.workspace.toggle_special("minimized"))  -- open/close the special

-- Focus between windows (the arrows)
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- ── The scrolling layout's tape (global; see appearance.lua) ────────────────
-- `move` scrolls the VIEW without touching the focus; with follow_mouse=1 (input.lua) passing the
-- mouse over the column that came in is enough for it to receive the keyboard. The arrows above
-- still hold: follow_focus (the default) already brings the focused column into view.
--
-- NO GUARD because ALL the workspaces are scrolling. If any goes back to dwindle, reintroducing
-- the guard is MANDATORY: a bind is global, a layout message is not, and on dwindle Hyprland
-- answers "Unknown dwindle layoutmsg" emitting ONE NOTIFICATION PER EVENT, so with the thumbwheel
-- in a burst the screen becomes a wall of toasts. And pcall does not help: checkResult emits the
-- notification and returns {ok=false} without raising a Lua error. The guard (the version in git,
-- commit 7f74ae8) filtered by `hl.get_active_workspace().id`, because the workspace object does
-- NOT expose `layout`; inside a lambda the dispatch is `hl.dispatch(d)`, never `d()`
-- ("dispatcher objects cannot be called directly").
hl.bind(mainMod .. " + comma",          hl.dsp.layout("move -col"))       -- tape left, 1 column
hl.bind(mainMod .. " + period",         hl.dsp.layout("move +col"))       -- tape right, 1 column
-- The MX Master's thumbwheel = SUPER plus the horizontal wheel. logiops does NOT divert the wheel
-- anymore (mouse.nix): it goes back to emitting native REL_HWHEEL, so horizontal scrolling inside
-- the apps (VS Code, a wide table) works normally, and the tape only moves with SUPER held.
-- The `binds:scroll_event_delay` ceiling (300ms, ~3 firings/s) stopped being a problem: it was
-- fatal for smooth PIXEL scrolling, but for a COLUMN jump 3/s is plenty, all the more with
-- column_width=1.0, where one column is already the whole screen.
hl.bind(mainMod .. " + mouse_left",     hl.dsp.layout("move -col"))       -- thumbwheel left
hl.bind(mainMod .. " + mouse_right",    hl.dsp.layout("move +col"))       -- thumbwheel right
-- The VERTICAL wheel moves along the tape too (it used to switch workspaces, which was never
-- used, since a workspace is always keyboard: SUPER+1-8 / TAB). With no SUPER the wheel behaves
-- normally in the apps. The direction was set BY HAND, by testing: scrolling DOWN advances toward
-- the side you use most.
hl.bind(mainMod .. " + mouse_down",     hl.dsp.layout("move -col"))       -- wheel down = forward
hl.bind(mainMod .. " + mouse_up",       hl.dsp.layout("move +col"))       -- wheel up = back
-- Reordering and resizing columns. swapcol moves the WHOLE COLUMN (the stack along with it) and
-- wraps at the ends; to move a single window out of a stack, expel (SUPER+O) first.
hl.bind(mainMod .. " + SHIFT + comma",  hl.dsp.layout("swapcol l"))       -- swap with the column on the left
hl.bind(mainMod .. " + SHIFT + period", hl.dsp.layout("swapcol r"))       -- swap with the column on the right
hl.bind(mainMod .. " + ALT + comma",    hl.dsp.layout("colresize -conf")) -- cycle the width down, ONLY the active column
hl.bind(mainMod .. " + ALT + period",   hl.dsp.layout("colresize +conf")) -- cycle the width up, ONLY the active column
-- ── View modes: they change the WHOLE tape (the ALT+,/. above is only the active column) ──
-- `fit all` is the "see everything at once" mode: it RESIZES and REPOSITIONS the columns so they
-- all fit on the screen, adapting to how many there are (2 windows give 951px each; 3 give
-- ~633px). It differs from `colresize all 0.5`, which forces 2-per-screen even with 5 windows
-- open. Careful: `colresize all N` on its own does NOT bring the view along, since I shrank 2
-- columns to 0.5 and both ended up off screen, to the left. `fit all` does both things.
hl.bind(mainMod .. " + CTRL + G",       hl.dsp.layout("fit all"))           -- SEE EVERYTHING: it squeezes the whole tape onto the screen
hl.bind(mainMod .. " + CTRL + period",  hl.dsp.layout("colresize all 1.0")) -- FOCUS: everything at 100% (1 window per screen)
hl.bind(mainMod .. " + CTRL + comma",   hl.dsp.layout("colresize all 0.5")) -- everything at 50% (2 side by side, fixed)
-- Stacking and unstacking windows inside the column
hl.bind(mainMod .. " + I",              hl.dsp.layout("consume"))         -- pull the window into the previous column
hl.bind(mainMod .. " + O",              hl.dsp.layout("expel"))           -- expel the window into a column of its own
-- `fit active` and NOT `fit_into_view`: the wiki documents the second, but 0.55.4 answers "no
-- such layoutmsg for scrolling". Every layout message requires a FOCUSED window (with no focus
-- they return "no focused window" and do nothing).
hl.bind(mainMod .. " + G",              hl.dsp.layout("fit active"))      -- recenter the active column
hl.bind(mainMod .. " + SHIFT + G",      hl.dsp.layout("fit expand"))      -- expand the window into the free space

-- Focus by monitor: F1 = the LG (main) · F2 = the TV (secondary). The names: my.monitors.
hl.bind(mainMod .. " + F1", hl.dsp.focus({ monitor = M.primary }))
hl.bind(mainMod .. " + F2", hl.dsp.focus({ monitor = M.secondary }))

-- Turning the TV (HDMI-A-3) on and off in Hyprland, by hand. The TV keeps the HDMI link alive
-- while off, so DRM still says "connected", monitor-watch receives no event and a "ghost monitor"
-- is left over. Turning it off pulls workspaces 5 to 8 back onto the LG; turning it on restores
-- them.
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("monitor-toggle"))

-- Workspaces 1 to 8 (SUPER switches; SUPER+SHIFT moves the window). 1-4 on the LG, 5-8 on the TV.
for i = 1, 8 do
  hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }))
  hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

-- Relative navigation (the previous/next workspace). KEYBOARD ONLY: the mouse wheel left here and
-- went to the tape (the scrolling block above), since switching workspaces on scroll was never
-- used, and the tape is what makes you want to scroll with the mouse.
hl.bind(mainMod .. " + TAB",         hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }))

-- Moving the active window between monitors: CTRL+left to the TV (on the left), CTRL+right to the LG (on the right).
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.move({ monitor = M.secondary }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ monitor = M.primary }))

-- Mouse: move / resize the window. The RESIZE is what puts one window beside another with the
-- mouse: scrolling implements a real resize-drag (the left border keeps the right one still by
-- adjusting the camera; the right border keeps the left one fixed), and shrinking the column
-- reveals its neighbor. The DRAG does not do that; see the middle click bind below.
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- "Arrange side by side", in one click. It exists because on scrolling EVERY way of moving a
-- window sideways (dragging, window.swap, window.move) STACKS it into the destination column,
-- checked on all three, and it is hardcoded in CScrollingAlgorithm. There is no horizontal drop.
-- So instead of fighting the drag, this bind UNDOES and normalizes: expel takes the window out of
-- any stack (into a column of its own) and fit all shows the whole tape on the screen.
-- A lambda plus hl.dispatch because a bind accepts only ONE dispatcher, and here there are two in
-- order.
local expelCol, fitAll = hl.dsp.layout("expel"), hl.dsp.layout("fit all")
hl.bind(mainMod .. " + mouse:274", function()                                     -- middle click: unstack plus show everything
  hl.dispatch(expelCol)
  return hl.dispatch(fitAll)
end)

-- ── Media / volume / brightness keys ────────────────────────────────────────
-- locked = it works with the screen locked; repeating = it repeats while held.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })  -- volume up (capped at 100%)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })  -- volume down
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })  -- mute the output
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })  -- mute the microphone
-- play/pause/next/prev through playerctl (locked only; repeating makes no sense).
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
-- brightness = hyprsunset's gamma (a desktop with no backlight); the OSD is Quickshell's own.
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightness-osd up"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightness-osd down"), { locked = true, repeating = true })
-- Brightness (gamma), since the keyboard has no brightness keys:
-- SHIFT+VolUp = brighter · SHIFT+VolDown = darker · SUPER+SHIFT+B = reset (100%).
-- The reset left SHIFT+code:19 (the physical 0 key): binding that CONSUMED the keystroke and, on
-- ABNT2, ")" is Shift+0, so there was no closing a parenthesis. SUPER+SHIFT+B steals no typing
-- key at all.
hl.bind("SHIFT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("brightness-osd up"),    { locked = true, repeating = true })
hl.bind("SHIFT + XF86AudioLowerVolume", hl.dsp.exec_cmd("brightness-osd down"),  { locked = true, repeating = true })
hl.bind(mainMod .. " + SHIFT + B",      hl.dsp.exec_cmd("brightness-osd reset"), { locked = true })

-- Screenshot (Flameshot v14). Print = the native flow (the picker plus a mouse click).
-- SUPER+SHIFT+S = the KEYBOARD flow (Arch parity): it opens the picker and enters the
-- "screenshot" submap, where 1 = the TV (secondary), 2 = the main one and Esc cancels. v14 ALWAYS
-- shows the picker on a multi-monitor setup; the scripts (home/apps/flameshot.nix) synthesize the
-- click on the preview and reset the submap on their own. It saves into ~/Pictures/Screenshots.
hl.bind("Print",                   hl.dsp.exec_cmd("flameshot gui"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("flameshot-screenshot"))

hl.define_submap("screenshot", function()
  -- positional: 1 = the LEFT screen (the TV), 2 = the RIGHT screen (the main LG).
  hl.bind("1",      hl.dsp.exec_cmd("flameshot-pick " .. M.secondary)) -- secondary (the TV, on the left)
  hl.bind("2",      hl.dsp.exec_cmd("flameshot-pick " .. M.primary))     -- main (the LG, on the right)
  hl.bind("escape", hl.dsp.exec_cmd("flameshot-cancel"))        -- cancel plus leave the submap
end)

-- ── The blue light filter (hyprsunset) ──────────────────────────────────────
-- The service (home/hyprsunset.nix) already changes the temperature by time of day on its own;
-- these binds are a one-off MANUAL override through IPC (`hyprctl hyprsunset`), and they hold
-- until the schedule's next profile takes over. F9 turns the whole service on and off.
hl.bind(mainMod .. " + F9",         hl.dsp.exec_cmd("systemctl --user is-active --quiet hyprsunset && systemctl --user stop hyprsunset || systemctl --user start hyprsunset")) -- toggle the service
hl.bind(mainMod .. " + SHIFT + F9", hl.dsp.exec_cmd("hyprctl hyprsunset identity"))         -- filter OFF (natural colors)
hl.bind(mainMod .. " + CTRL + F9",  hl.dsp.exec_cmd("hyprctl hyprsunset temperature 3000")) -- night (warm)
hl.bind(mainMod .. " + ALT + F9",   hl.dsp.exec_cmd("hyprctl hyprsunset temperature 2000")) -- the small hours (very warm)
