-- ── Monitors ───────────────────────────────────────────────────────────────
-- The connector names were confirmed through `hyprctl monitors` (Wayland/Arc):
--   primary   = the LG ULTRAGEAR (1080p 144Hz), the MAIN one, at the origin 0x0
--   secondary = the LG TV, on the left (a negative x), at Full HD (1920x1080@60).
-- Adapting to a disconnected TV: with the main one at 0x0, the LG stands alone with no ghost
-- offset, and workspaces 5 to 8 fall back onto it automatically.
-- Data generated by Nix, with a SELF-CONTAINED FALLBACK: if the file is missing (the 1st boot
-- before the rebuild, or new data not generated yet), the dofile BLOWS UP and aborts the config,
-- and since "autostart" comes later in the load order, the session comes up with no services.
-- Do NOT use a global helper: Hyprland does not share globals between the dofile calls.
local ok_M, M = pcall(dofile, os.getenv("HOME") .. "/.config/theme/monitors.lua")
if not ok_M or type(M) ~= "table" then M = { primary = "DP-2", secondary = "HDMI-A-3" } end

hl.monitor({ output = M.primary,     mode = "1920x1080@143.98", position = "0x0",     scale = 1 })
hl.monitor({ output = M.secondary, mode = "1920x1080@60",     position = "-1920x0", scale = 1 })
hl.monitor({ output = "",         mode = "preferred",        position = "auto",    scale = "auto" })

-- 4 workspaces per monitor: 1 to 4 on the LG (the main one), 5 to 8 on the TV (the secondary).
-- The connector names come from Nix (my.monitors), an SSOT in home/desktop/monitors.nix.
-- default:true = the workspace that opens on each monitor when the session boots.
-- No `layout` here: scrolling is global (appearance.lua) ever since the trial on ws 2 and 6 was
-- approved in use. If there is ever a dwindle workspace again, the tape's binds need the guard
-- back, otherwise dwindle spits an error toast PER EVENT (see the notes).
hl.workspace_rule({ workspace = "1", monitor = M.primary,     default = true })
hl.workspace_rule({ workspace = "2", monitor = M.primary })
hl.workspace_rule({ workspace = "3", monitor = M.primary })
hl.workspace_rule({ workspace = "4", monitor = M.primary })
hl.workspace_rule({ workspace = "5", monitor = M.secondary, default = true })
hl.workspace_rule({ workspace = "6", monitor = M.secondary })
hl.workspace_rule({ workspace = "7", monitor = M.secondary })
hl.workspace_rule({ workspace = "8", monitor = M.secondary })
