-- ── Window rules ────────────────────────────────────────────────────────────
-- Ported from the Arch window-rules.conf, adapted to the Lua 0.55 API.

-- A subtle transparency on everything: 0.98 active / 0.96 inactive (contrast plus the wallpaper).
-- Data generated by Nix, with a SELF-CONTAINED FALLBACK: if the file is missing (the 1st boot
-- before the rebuild, or new data not generated yet), the dofile BLOWS UP and aborts the config,
-- and since "autostart" comes later in the load order, the session comes up with no services.
-- Do NOT use a global helper: Hyprland does not share globals between the dofile calls.
local ok_M, M = pcall(dofile, os.getenv("HOME") .. "/.config/theme/monitors.lua")
if not ok_M or type(M) ~= "table" then M = { primary = "DP-2", secondary = "HDMI-A-3" } end

hl.window_rule({ match = { class = ".*" }, opacity = "0.98 0.96" })
-- It ignores the apps' "maximize" requests (which behaves better under tiling).
hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })
-- The XWayland drag fix: windows with no class/title, floating, that steal focus.
hl.window_rule({
  match = { class = "^$", title = "^$", xwayland = 1, float = 1, fullscreen = 0 },
  suppress_event = "activate activatefocus",
})
-- Picture-in-Picture (a detached video) always 100% opaque.
hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, opacity = "1.0" })
-- Ascension (a private WoW through Wine): floating and centered on the LG, opaque, with no
-- idle-lock.
hl.window_rule({
  match = { class = "^(ascension\\.exe)$" },
  float = true,
  monitor = M.primary,
  size = "1920 1080",
  center = true,
  fullscreen = true,
  opacity = "1.0 override 1.0 override",
  idle_inhibit = "focus",
})

-- ── Screenshot (Flameshot v14 through the portal) ───────────────────────────
-- The config is in home/apps/flameshot.nix; the capture goes through xdg-desktop-portal (-wlr).
-- The rule was ported from my Arch (v14): the -1920/3840 stretch of the OLD flow (v13/grim)
-- BREAKS v14, since v14 opens a monitor PICKER (a normal window) and then a fullscreen overlay on
-- the chosen monitor. Forcing a giant move/size scrambles the picker. Here we only leave it
-- floating and centered, with no animation; suppress_event=fullscreen keeps the overlay a
-- floating window (it does not enter Hyprland's fullscreen, so there is no wallpaper flash on
-- close). opacity/no_blur/no_shadow: the overlay is a frozen frame, it does not inherit the
-- global transparency/blur. Matching by TITLE: on this box the flameshot window (both the monitor
-- picker and the overlay) has an EMPTY class and the title "flameshot". With no float it falls
-- into dwindle's tiling (born squeezed into half a screen), which is where the "bug" came from.
hl.window_rule({
  name = "flameshot-v14-overlay",
  match = { title = "^flameshot$" },

  no_anim = true,
  float = true,
  center = true,
  pin = false,
  opacity = "1.0 override 1.0 override",
  no_blur = true,
  no_shadow = true,
  rounding = 0,
  suppress_event = "fullscreen",
})
