# MONITOR data for the HOT-RELOAD consumers (Lua, QML), which Nix cannot write into. The option
# is system/desktop/monitors.nix; the two panels and their modes: docs/notes/hardware/monitors.md
{ osConfig, ... }:

let
  cfg = osConfig.my.monitors;
in
{
  # Data for Hyprland: monitors/rules/keybinds.lua dofile it and use the table.
  home.file.".config/theme/monitors.lua".text = ''
    -- Generated by Nix (my.monitors). Do NOT edit by hand; the source is system/desktop/monitors.nix.
    return {
      primary = "${cfg.primary}",
      secondary = "${cfg.secondary}",
    }
  '';

  # Data for Quickshell: Theme.qml reads it through FileView plus JsonAdapter.
  home.file.".config/theme/monitors.json".text = builtins.toJSON {
    inherit (cfg) primary secondary;
  };
}
