# MONITOR data for the ones that HOT-RELOAD (Hyprland in Lua and Quickshell in QML): they read a
# file at runtime, and Nix does not write inside the symlinked trees of ~/.config/hypr and
# ~/.config/quickshell, so the value leaves the option and becomes a file here (the same mechanics
# as the palette in home/desktop/palette.nix).
#
# THE OPTION itself does NOT live here anymore: `my.monitors` has been a system option since
# 04/08/2026 (system/desktop/monitors.nix), because Sunshine also needs the connector to pick which
# monitor to capture. Here it is only read, through `osConfig`.
{ osConfig, ... }:

let
  cfg = osConfig.my.monitors;
in
{
  # Data for Hyprland: monitors/rules/keybinds.lua dofile it and use the table.
  home.file.".config/theme/monitors.lua".text = ''
    -- Generated by Nix (my.monitors). Do NOT edit by hand; the source is system/desktop/monitors.nix.
    return {
      primary = "${cfg.primary}",
      secondary = "${cfg.secondary}",
    }
  '';

  # Data for Quickshell: Theme.qml reads it through FileView plus JsonAdapter.
  home.file.".config/theme/monitors.json".text = builtins.toJSON {
    inherit (cfg) primary secondary;
  };
}
