dhcp.main=dnsmasq
dhcp.main.domainneeded='1'
dhcp.main.boguspriv='1'
dhcp.main.filterwin2k='0'
dhcp.main.localise_queries='1'
dhcp.main.rebind_protection='1'
dhcp.main.rebind_localhost='1'
dhcp.main.local='/lan/'
dhcp.main.domain='lan'
dhcp.main.expandhosts='1'
dhcp.main.nonegcache='0'
dhcp.main.cachesize='1000'
dhcp.main.authoritative='1'
dhcp.main.readethers='1'
dhcp.main.leasefile='/tmp/dhcp.leases'
dhcp.main.resolvfile='/tmp/resolv.conf.d/resolv.conf.auto'
dhcp.main.localservice='1'
dhcp.main.ednspacket_max='1232'
dhcp.main.filter_aaaa='0'
dhcp.main.filter_a='0'
dhcp.main.server='/fai2008.ufscar.br/200.136.209.252' '/fai2008.ufscar.br/200.136.209.247' '/vpn.v1cferr.dev/127.0.0.1#5053' '/vpn.v1cferr.dev/127.0.0.1#5054' '/mask.icloud.com/' '/mask-h2.icloud.com/' '/use-application-dns.net/' '127.0.0.1#5053' '127.0.0.1#5054'
dhcp.main.address='/v1cferr.dev/192.168.1.10' '/cesar-ssh.v1cferr.dev/192.168.1.40'
dhcp.main.rebind_domain='fai2008.ufscar.br'
dhcp.main.doh_backup_noresolv='-1'
dhcp.main.noresolv='1'
dhcp.main.doh_backup_server='/fai2008.ufscar.br/200.136.209.252' '/fai2008.ufscar.br/200.136.209.247' '/vpn.v1cferr.dev/127.0.0.1#5053' '/vpn.v1cferr.dev/127.0.0.1#5054' '/mask.icloud.com/' '/mask-h2.icloud.com/' '/use-application-dns.net/' '127.0.0.1#5053' '127.0.0.1#5054'
dhcp.main.doh_server='127.0.0.1#5053' '127.0.0.1#5054'
dhcp.main.serversfile='/var/run/adblock-fast/dnsmasq.servers'
dhcp.lan=dhcp
dhcp.lan.interface='lan'
dhcp.lan.start='100'
dhcp.lan.limit='150'
dhcp.lan.leasetime='12h'
dhcp.lan.dhcpv4='server'
dhcp.lan.dhcpv6='server'
dhcp.lan.ra='server'
dhcp.lan.ra_flags='managed-config' 'other-config'
dhcp.lan.ra_preference='medium'
dhcp.lan.instance='main'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.leasefile='/tmp/odhcpd.leases'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'
dhcp.odhcpd.piodir='/tmp/odhcpd-piodir'
dhcp.odhcpd.hostsdir='/tmp/hosts'
dhcp.@host[0]=host
dhcp.@host[0].name='TV-Samsung-Sala'
dhcp.@host[0].mac='54:BD:79:DB:FA:03'
dhcp.@host[0].ip='192.168.1.20'
dhcp.@host[1]=host
dhcp.@host[1].name='v1cferr-nixos'
dhcp.@host[1].mac='7C:10:C9:A1:F4:E5'
dhcp.@host[1].ip='192.168.1.10'
dhcp.@host[2]=host
dhcp.@host[2].name='Victor-M51'
dhcp.@host[2].mac='68:7D:6B:ED:51:F3'
dhcp.@host[2].ip='192.168.1.30'
dhcp.arch_cesar=host
dhcp.arch_cesar.name='arch-cesar'
dhcp.arch_cesar.mac='74:56:3C:F2:B6:48'
dhcp.arch_cesar.ip='192.168.1.40'
dhcp.@domain[0]=domain
dhcp.@domain[0].name='t480'
dhcp.@domain[0].ip='10.10.10.6'
dhcp.blocked=dnsmasq
dhcp.blocked.port='5453'
dhcp.blocked.localservice='1'
dhcp.blocked.noresolv='1'
dhcp.blocked.cachesize='0'
dhcp.blocked.domainneeded='0'
dhcp.blocked.boguspriv='0'
dhcp.blocked.rebind_protection='0'
dhcp.blocked.server='127.0.0.1#53' '/reddit.com/' '/redd.it/' '/redditstatic.com/' '/redditmedia.com/'
