dhcp.@dnsmasq[0]=dnsmasq
dhcp.@dnsmasq[0].domainneeded='1'
dhcp.@dnsmasq[0].boguspriv='1'
dhcp.@dnsmasq[0].filterwin2k='0'
dhcp.@dnsmasq[0].localise_queries='1'
dhcp.@dnsmasq[0].rebind_protection='1'
dhcp.@dnsmasq[0].rebind_localhost='1'
dhcp.@dnsmasq[0].local='/lan/'
dhcp.@dnsmasq[0].domain='lan'
dhcp.@dnsmasq[0].expandhosts='1'
dhcp.@dnsmasq[0].nonegcache='0'
dhcp.@dnsmasq[0].cachesize='1000'
dhcp.@dnsmasq[0].authoritative='1'
dhcp.@dnsmasq[0].readethers='1'
dhcp.@dnsmasq[0].leasefile='/tmp/dhcp.leases'
dhcp.@dnsmasq[0].resolvfile='/tmp/resolv.conf.d/resolv.conf.auto'
dhcp.@dnsmasq[0].localservice='1'
dhcp.@dnsmasq[0].ednspacket_max='1232'
dhcp.@dnsmasq[0].filter_aaaa='0'
dhcp.@dnsmasq[0].filter_a='0'
dhcp.@dnsmasq[0].server='/mask.icloud.com/' '/mask-h2.icloud.com/' '/use-application-dns.net/' '127.0.0.1#5053' '127.0.0.1#5054' '/fai2008.ufscar.br/200.136.209.252' '/fai2008.ufscar.br/200.136.209.247' '/vpn.v1cferr.dev/127.0.0.1#5053' '/vpn.v1cferr.dev/127.0.0.1#5054'
dhcp.@dnsmasq[0].address='/v1cferr.dev/192.168.1.10' '/cesar-ssh.v1cferr.dev/192.168.1.40'
dhcp.@dnsmasq[0].doh_backup_noresolv='-1'
dhcp.@dnsmasq[0].noresolv='1'
dhcp.@dnsmasq[0].doh_backup_server='/mask.icloud.com/' '/mask-h2.icloud.com/' '/use-application-dns.net/' '127.0.0.1#5053' '127.0.0.1#5054'
dhcp.@dnsmasq[0].doh_server='127.0.0.1#5053' '127.0.0.1#5054'
dhcp.@dnsmasq[0].rebind_domain='fai2008.ufscar.br'
dhcp.lan=dhcp
dhcp.lan.interface='lan'
dhcp.lan.start='100'
dhcp.lan.limit='150'
dhcp.lan.leasetime='12h'
dhcp.lan.dhcpv4='server'
dhcp.lan.dhcpv6='server'
dhcp.lan.ra='server'
dhcp.lan.ra_flags='managed-config' 'other-config'
dhcp.lan.ra_preference='medium'
dhcp.odhcpd=odhcpd
dhcp.odhcpd.leasefile='/tmp/odhcpd.leases'
dhcp.odhcpd.leasetrigger='/usr/sbin/odhcpd-update'
dhcp.odhcpd.loglevel='4'
dhcp.odhcpd.piodir='/tmp/odhcpd-piodir'
dhcp.odhcpd.hostsdir='/tmp/hosts'
dhcp.@host[0]=host
dhcp.@host[0].name='TV-Samsung-Sala'
dhcp.@host[0].mac='54:BD:79:DB:FA:03'
dhcp.@host[0].ip='192.168.1.20'
dhcp.@host[1]=host
dhcp.@host[1].name='v1cferr-nixos'
dhcp.@host[1].mac='7C:10:C9:A1:F4:E5'
dhcp.@host[1].ip='192.168.1.10'
dhcp.@host[2]=host
dhcp.@host[2].name='Victor-M51'
dhcp.@host[2].mac='68:7D:6B:ED:51:F3'
dhcp.@host[2].ip='192.168.1.30'
dhcp.arch_cesar=host
dhcp.arch_cesar.name='arch-cesar'
dhcp.arch_cesar.mac='74:56:3C:F2:B6:48'
dhcp.arch_cesar.ip='192.168.1.40'
