nlbwmon.@nlbwmon[0]=nlbwmon
nlbwmon.@nlbwmon[0].netlink_buffer_size='524288'
nlbwmon.@nlbwmon[0].commit_interval='24h'
nlbwmon.@nlbwmon[0].refresh_interval='30s'
nlbwmon.@nlbwmon[0].database_directory='/var/lib/nlbwmon'
nlbwmon.@nlbwmon[0].database_generations='10'
nlbwmon.@nlbwmon[0].database_interval='1'
nlbwmon.@nlbwmon[0].database_limit='10000'
nlbwmon.@nlbwmon[0].protocol_database='/usr/share/nlbwmon/protocols'
nlbwmon.@nlbwmon[0].local_network='192.168.0.0/16' '172.16.0.0/12' '10.0.0.0/8' 'lan'
