sqm.eth1=queue
sqm.eth1.enabled='0'
sqm.eth1.interface='pppoe-wan'
sqm.eth1.download='552000'
sqm.eth1.upload='276000'
sqm.eth1.qdisc='cake'
sqm.eth1.script='piece_of_cake.qos'
sqm.eth1.linklayer='ethernet'
sqm.eth1.use_mq='0'
sqm.eth1.debug_logging='1'
sqm.eth1.verbosity='5'
sqm.eth1.overhead='8'
