attendedsysupgrade.server=server
attendedsysupgrade.server.url='https://sysupgrade.openwrt.org'
attendedsysupgrade.client=client
attendedsysupgrade.client.upgrade_packages='1'
attendedsysupgrade.client.auto_search='1'
attendedsysupgrade.client.advanced_mode='1'
attendedsysupgrade.client.login_check_for_upgrades='1'
attendedsysupgrade.owut=owut
