banip.global=banip
banip.global.ban_enabled='1'
banip.global.ban_debug='0'
banip.global.ban_autodetect='1'
banip.global.ban_logterm='Exit before auth from' 'luci: failed login'
banip.global.ban_feed='feodo' 'dshield' 'threat'
banip.global.ban_loginbound='1'
banip.global.ban_logoutbound='1'
banip.global.ban_loglimit='0'
banip.global.ban_fetchcmd='curl'
banip.global.ban_protov4='1'
banip.global.ban_ifv4='wan'
banip.global.ban_protov6='1'
banip.global.ban_ifv6='wan_6'
banip.global.ban_dev='pppoe-wan'
