system.@system[0]=system
system.@system[0].hostname='OpenWrt'
system.@system[0].timezone='<-03>3'
system.@system[0].zonename='America/Sao_Paulo'
system.@system[0].ttylogin='0'
system.@system[0].log_size='128'
system.@system[0].urandom_seed='0'
system.@system[0].log_proto='udp'
system.@system[0].conloglevel='8'
system.@system[0].cronloglevel='7'
system.ntp=timeserver
system.ntp.server='0.openwrt.pool.ntp.org' '1.openwrt.pool.ntp.org' '2.openwrt.pool.ntp.org' '3.openwrt.pool.ntp.org'
system.led_wan=led
system.led_wan.name='wan'
system.led_wan.sysfs='blue:wan'
system.led_wan.trigger='netdev'
system.led_wan.mode='link tx rx'
system.led_wan.dev='wan'
