# The overlays every host's nixpkgs gets, IN ORDER: unstable.*, the patched and vendored builds,
# ./pkgs and ./tools. Why each one exists and when it leaves: docs/notes/repo/flake.md
{ inputs, system }:

let
  inherit (inputs) nixpkgs nixpkgs-unstable;

  # ONE unstable instance, hoisted OUT of the overlay on purpose: inside it the import would run
  # per pkgs instance AND per splice (pkgsi686Linux), which is the OOM everyone hits.
  pkgsUnstable = import nixpkgs-unstable {
    inherit system;
    config.allowUnfree = true;
  };

  # It exposes `pkgs.unstable.<pkg>` while everything else stays on the stable base, which is what
  # gives the choice PER PACKAGE.
  overlayUnstable = _: _: { unstable = pkgsUnstable; };

  # Spotify: `--no-zygote` baked into the PACKAGE (not the autostart), or CEF dies of SIGTRAP in
  # 270ms with no window. REMOVE when it opens without it: docs/notes/repo/flake.md
  overlaySpotifyNoZygote = _: prev: {
    unstable = prev.unstable // {
      spotify = prev.unstable.spotify.overrideAttrs (old: {
        postFixup = (old.postFixup or "") + ''
          wrapProgram $out/bin/spotify --add-flags "--no-zygote"
        '';
      });
    };
  };

  # unstable's RECIPE with the SRC from pkgs/vscode. `import` and not callPackage, so the result
  # keeps nixpkgs' `.override` (modules/home/apps/vscode.nix passes commandLineArgs through it).
  overlayVscode = final: prev: {
    unstable = prev.unstable // {
      vscode = import ../pkgs/vscode/package.nix {
        inherit (final) lib fetchurl callPackage;
        inherit (prev.unstable) vscode;
      };
    };
  };

  # btop with Intel Xe: TEMPORARY. nixpkgs' btop has GPU on, but its Intel backend is i915-ONLY and
  # the B580 is xe. REMOVE when PR #1457 lands in the channel: docs/notes/repo/flake.md
  overlayBtopXe = _: prev: {
    btop = prev.btop.overrideAttrs (old: {
      version = "1.4.7-unstable-2026-07-20";
      src = prev.fetchFromGitHub {
        owner = "deveworld";
        repo = "btop";
        rev = "76530c80dd6184ccb72d7048c2589afdc4bdee52"; # feature/xe-gpu-support, head of PR #1457
        hash = "sha256-zBzr2NmekUvK8Hae5N/8qu9OdfGK5+Kzu7maZOVK/sY=";
      };
      doInstallCheck = false;
      meta = old.meta // {
        changelog = "https://github.com/aristocratos/btop/pull/1457";
      };
    });
  };

  # OpenRGB that knows the Arc B580: TEMPORARY. The channel ships 1.0rc3, which predates the
  # ASRock GPU controller entirely, so no version of it can drive this card. Master can, with
  # three patches on top: someone else's merge request for the Intel bus, plus the two that
  # came out of this machine. REMOVE when they land and the channel catches up, which also
  # deletes ../pkgs/openrgb: docs/notes/hardware/gpu-rgb.md
  overlayOpenrgbArc = _: prev: {
    openrgb = prev.openrgb.overrideAttrs (old: {
      version = "1.0-unstable-2026-09-18";
      src = prev.fetchFromCodeberg {
        owner = "OpenRGB";
        repo = "OpenRGB";
        rev = "cd44e41d462629410a806119694a773e88449ce1";
        hash = "sha256-0Hx23P6x9orNmCu+t14E2XyO04FS+KOJjf8dA9ZPoxQ=";
      };

      # NOT `old.patches ++`: the channel's own patch does not apply to master, so ours is a
      # rebase of it and REPLACES it. Dropping it instead would quietly break `withPlugins`.
      patches = [
        ../pkgs/openrgb/system-plugins-env.patch
        ../pkgs/openrgb/intel-gpu-i2c-bus.patch
        ../pkgs/openrgb/asrock-arc-b580-steel-legend.patch
        ../pkgs/openrgb/asrock-gpu-shutdown.patch
      ];

      # The channel patches a script that master DELETED: since 1.0 the udev rules are
      # generated by the binary itself, so the substitution has nothing to stand on.
      postPatch = "";

      # `lrelease` moved to qttools, and master's build calls it. The channel has qttools in
      # buildInputs, which does NOT put it on PATH, and qmake bakes qtbase's path into the
      # Makefile anyway, so the assignment has to happen after qmake has run.
      nativeBuildInputs = old.nativeBuildInputs ++ [ prev.qt6Packages.qttools ];
      postConfigure = ''
        sed -i "s|${prev.qt6Packages.qtbase}/bin/lrelease|${prev.qt6Packages.qttools}/bin/lrelease|g" Makefile
      '';

      # And this is the other half of that deletion: `make install` never installs rules, so
      # without this the package has no `lib/udev/rules.d` and `services.udev.packages`
      # silently installs nothing. Offscreen because the binary is a Qt app even here.
      # The `sed` is the channel's own substitution, moved: it used to patch the generator
      # script, and the strings now live inside the binary, so the only place left to catch
      # them is the output. NixOS refuses a rules file that references /usr/bin/env.
      postInstall = old.postInstall + ''
        install -d $out/lib/udev/rules.d
        QT_QPA_PLATFORM=offscreen $out/bin/openrgb --print-udev-rules \
          | sed "s|/usr/bin/env chmod|${prev.coreutils}/bin/chmod|g" \
          > $out/lib/udev/rules.d/60-openrgb.rules
      '';
    });
  };

  # LOCAL packages in ./pkgs, exposed as `pkgs.<name>`; callPackage injects the deps. Most are
  # outside nixpkgs, `codex` REPLACES the one there (the note says why).
  localPkgs = final: {
    claude-code-discord-status = final.callPackage ../pkgs/claude-code-discord-status.nix { };
    azure-mcp = final.callPackage ../pkgs/azure-mcp.nix { }; # Azure MCP Server (`azmcp`), only in claude-fai
    nxbender = final.callPackage ../pkgs/nxbender.nix { }; # FOSS client for the SonicWall VPN (FAI)
    codex = final.callPackage ../pkgs/codex/package.nix { }; # OpenAI's CLI, the OFFICIAL release binary
    antigravity-cli = final.callPackage ../pkgs/antigravity-cli/package.nix { }; # Google's agent CLI (`agy`)
    basic-memory = final.callPackage ../pkgs/basic-memory.nix { inherit inputs; }; # `bm`, the MCP memory
    curseforge = final.callPackage ../pkgs/curseforge/package.nix { }; # official modpack AppImage (unfree)
    curseforge-fix-perms = final.callPackage ../pkgs/curseforge-fix-perms.nix { }; # +x on what the app unpacks
    razer-dpi = final.callPackage ../pkgs/razer-dpi.nix { }; # the Razer mouse's live DPI, over hidraw
    notify = final.callPackage ../pkgs/notify.nix { }; # the ntfy push, shared by the shell and sshd's PAM
  };

  # The repo's OWN tools in ./tools: they check, measure and maintain this tree, and are not
  # software the machine runs. Same overlay, so `nix run .#<tool>` and the hooks reach them.
  localTools = final: {
    docs-links = final.callPackage ../tools/docs-links.nix { }; # it fails when a docs/ pointer breaks
    prose-style = final.callPackage ../tools/prose-style.nix { }; # rule 17's bans, in prose and in a message
    qml-syntax = final.callPackage ../tools/qml-syntax.nix { }; # it fails on a .qml that does not parse
    data-syntax = final.callPackage ../tools/data-syntax.nix { }; # it fails on a .json/.toml that does not parse
    dead-config = final.callPackage ../tools/dead-config.nix { }; # it fails on declared-and-unused
    router-ssot = final.callPackage ../tools/router-ssot.nix { }; # it fails when the router's mirror diverges
    eval-metrics = final.callPackage ../tools/eval-metrics/package.nix { }; # what evaluating each host costs
    usage-audit = final.callPackage ../tools/usage-audit.nix { }; # each app next to the traces of its use
    rules-index = final.callPackage ../tools/rules-index.nix { }; # it fails on a citation of no live rule
    docs-site = final.callPackage ../tools/docs-site.nix { }; # docs/ built into the static site
    docs-site-check = final.callPackage ../tools/docs-site-check.nix { }; # the same build, at push time
  };
  overlayLocalPkgs =
    final: _:
    localPkgs final
    // localTools final
    // {
      # The skeleton every pkgs/<name>/bump.nix is built from, OUTSIDE localPkgs: it is a function.
      mkVendoredBump = import ../pkgs/lib/mk-vendored-bump.nix {
        inherit (final) writeShellApplication curl jq;
      };
      # Every package carrying a passthru.updateScript, DERIVED: a new one never touches `update`.
      vendored-bump = final.callPackage ../tools/vendored-bump.nix {
        packages =
          nixpkgs.lib.filterAttrs (_: p: p.updateScript or null != null) (
            nixpkgs.lib.getAttrs (builtins.attrNames (localPkgs final)) final
          )
          // {
            inherit (final.unstable) vscode; # not a ./pkgs package, but its src bumps the same way
          };
      };
    };

  # Claude Desktop: it forces the secret backend, since Electron does not recognize "Hyprland" and
  # falls back to plaintext, so the login is asked EVERY time. Only the fixpoint one is wrapped.
  overlayClaudeKeyring = _: prev: {
    claude-desktop = prev.claude-desktop.overrideAttrs (old: {
      postInstall = (old.postInstall or "") + ''
        wrapProgram $out/bin/claude-desktop --add-flags "--password-store=gnome-libsecret"
      '';
    });
  };
in
# unstable.* plus ./pkgs plus claude-desktop, as OVERLAYS so they build against THIS base and add
# no 3rd nixpkgs. The keyring one comes AFTER, since it re-wraps their package.
[
  overlayUnstable
  overlayVscode # AFTER overlayUnstable: it patches that `unstable.vscode`
  overlaySpotifyNoZygote # same: bakes in the flag without which Spotify does not open
  overlayBtopXe # temporary: Intel Xe GPU (Arc B580) until PR #1457 merges
  overlayOpenrgbArc # temporary: the Arc B580's RGB, until the merge requests land
  overlayLocalPkgs
  inputs.claude-desktop.overlays.default
  overlayClaudeKeyring
]
