# DISCORD RICH PRESENCE FOR CLAUDE CODE (user level): the daemon plus the config.
#
# The tool's trio: the hook (system/claude-code.nix, which POSTs the events) -> the daemon (here,
# which holds the Discord RPC connection plus a local HTTP server) -> the card on Discord. It
# needs the Discord client running (home/discord.nix), which exposes the IPC socket.
#
# Everything declarative: the package comes from the overlay (./pkgs), the config is generated by
# Nix and the daemon runs as a systemd --user service, WITHOUT the imperative
# `claude-presence setup` (which would mutate settings.json and bring the daemon up by hand).
# ═══════════════════════════════════════════════════════════════════════════
{
  pkgs,
  osConfig,
  lib,
  ...
}:

let
  ccds = pkgs.claude-code-discord-status;
  daemonEntry = "${ccds}/lib/node_modules/claude-code-discord-status/dist/daemon/index.js";
in
lib.mkIf osConfig.my.services.discord-rpc {
  home.packages = [ ccds ]; # the `claude-presence` CLI, for diagnosis (status/doctor/preview)

  # The config the daemon reads (loadConfig -> ~/.claude-presence/config.json). The DIRECTORY stays
  # writable so the daemon can write pid/log/aggregate; that is STATE, not config.
  home.file.".claude-presence/config.json".text = builtins.toJSON {
    discordClientId = "1472915568930848829"; # upstream's default public app
    daemonPort = 19452; # the daemon's local port (the default; the hook uses the same one)
    preset = "minimal"; # the activity card's style
    daemonPath = daemonEntry; # referenced only in the hook's autostart fallback
  };

  # The daemon: it comes up with the graphical session (Discord lives in it) and reconnects on its
  # own if Discord opens or closes later. A declared service means we do not depend on the tool's
  # own imperative autostart. It does not restart in a loop: with no Discord it just logs and
  # carries on.
  systemd.user.services.claude-presence-daemon = {
    Unit = {
      Description = "Claude Code's Discord Rich Presence (daemon)";
      After = [ "graphical-session.target" ];
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      ExecStart = "${pkgs.nodejs}/bin/node ${daemonEntry}";
      Restart = "on-failure";
      RestartSec = 5;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
