# The FAI workstation mounted as a local folder (~/FAI-workstation) through rclone SFTP plus a VFS
# cache, so it shows up in Dolphin as a normal folder, fast (a read/write cache, rereading from
# disk). It comes up ONLY when the FAI VPN connects (`vpn connect fai` starts the mount; a
# disconnect takes it down), since the host 200.136.209.229 only exists through the VPN, so there
# is no ghost/stale mount at boot (SSHFS would freeze Dolphin in that scenario; rclone fails clean
# and reconnects).
# SFTP through key_file (the SSH key that already exists), so ZERO secrets in nix.
{ config, ... }:

let
  ws = config.my.fai.workstation; # SSOT: home/net/fai-workstation.nix (rule 11)
in
{
  programs.rclone = {
    enable = true;
    remotes.faiws = {
      # The rclone.conf is generated by the module; only paths/host here (no secret).
      config = {
        type = "sftp";
        # host/user come from ws' SSOT (a workstation reachable only through the FAI VPN).
        inherit (ws) host user;
        key_file = "/home/v1cferr/.ssh/id_ed25519"; # an existing key (state, so backup)
        known_hosts_file = "/home/v1cferr/.ssh/known_hosts"; # the workstation is already trusted
      };
      mounts."/" = {
        # "/" = the workstation's whole root (not just the home). The user v1cferr sees what they
        # have permission to read; the rest shows up but stays inaccessible (normal for a
        # non-root).
        enable = true;
        autoMount = false; # it does NOT mount at boot; `vpn connect fai` brings it up (VPN-gated)
        mountPoint = "/home/v1cferr/FAI-workstation";
        options = {
          # "writes": READS go straight through (streaming, they do NOT pile up on disk), and only
          # what you write/copy is cached until it uploads. The disk stays lean. (Switch it to
          # "full" if you want maximum speed reopening files, at the cost of filling the cache.)
          vfs-cache-mode = "writes";
          vfs-cache-max-age = "6h"; # it evicts the write cache quickly
          vfs-cache-max-size = "2G"; # a low ceiling for the on-disk cache (~/.cache/rclone)
          dir-cache-time = "5m"; # the listing cached for 5min, so browsing is FAST (F5 reloads)
          buffer-size = "8M"; # read-ahead RAM per open file, low on purpose
          timeout = "30s"; # the I/O timeout (it does not hang forever if the VPN drops)
          contimeout = "15s"; # the connection timeout
        };
      };
    };
  };

  # The VPN comes up asynchronously (~10s until the tunnel/routes). Without this systemd would
  # give up after 5 quick failures (StartLimit) before the host became reachable. It retries every
  # 10s until it connects, and since `vpn connect fai` gives the start and `disconnect` gives the
  # stop, it does not loop forever when the VPN is intentionally off.
  systemd.user.services."rclone-mount:.@faiws" = {
    Unit.StartLimitIntervalSec = 0;
    Service.RestartSec = 10;
  };
}
