# ~/FAI-workstation: the workstation's root over rclone SFTP plus a VFS cache. VPN-GATED, since
# the host only exists through the tunnel and SSHFS would freeze Dolphin: docs/notes/fai-workstation.md
{ config, ... }:

let
  ws = config.my.fai.workstation; # SSOT: home/net/fai-workstation.nix (rule 11)
in
{
  programs.rclone = {
    enable = true;
    remotes.faiws = {
      # The rclone.conf is generated by the module; only paths/host here (no secret).
      config = {
        type = "sftp";
        # host/user come from ws' SSOT (a workstation reachable only through the FAI VPN).
        inherit (ws) host user;
        key_file = "/home/v1cferr/.ssh/id_ed25519"; # an existing key (state, so backup)
        known_hosts_file = "/home/v1cferr/.ssh/known_hosts"; # the workstation is already trusted
      };
      mounts."/" = {
        # "/" = the whole root: the user sees what they may read, and the rest is visible but closed.
        enable = true;
        autoMount = false; # it does NOT mount at boot; `vpn connect fai` brings it up (VPN-gated)
        mountPoint = "/home/v1cferr/FAI-workstation";
        options = {
          # "writes": READS stream through without piling up on disk; only what you write is cached.
          # Switch to "full" for faster reopening, at the cost of filling the cache.
          vfs-cache-mode = "writes";
          vfs-cache-max-age = "6h"; # it evicts the write cache quickly
          vfs-cache-max-size = "2G"; # a low ceiling for the on-disk cache (~/.cache/rclone)
          dir-cache-time = "5m"; # the listing cached for 5min, so browsing is FAST (F5 reloads)
          buffer-size = "8M"; # read-ahead RAM per open file, low on purpose
          timeout = "30s"; # the I/O timeout (it does not hang forever if the VPN drops)
          contimeout = "15s"; # the connection timeout
        };
      };
    };
  };

  # The VPN takes ~10s to route, so the StartLimit is cleared: systemd would otherwise give up
  # before the host was reachable. `vpn connect fai` starts it and `disconnect` stops it.
  systemd.user.services."rclone-mount:.@faiws" = {
    Unit.StartLimitIntervalSec = 0;
    Service.RestartSec = 10;
  };
}
